baseURL: https://farzadhayat.dev
languageCode: en-us
title: Farzad Hayat
theme: PaperMod

params:
  homeInfoParams:
    Title: "G'day ðŸ‘‹"
    Content: "I am a final-semester **Computer Science** student at **Queensland University of Technology**, currently seeking a Software Engineering internship in Australia or New Zealand. In my free time, I enjoy exploring open source software, partner dancing, and cooking."

  socialIcons:
    - name: "Email"
      url: "mailto:hello@farzadhayat.dev"
    - name: "GitHub"
      url: "https://github.com/FarzadHayat/"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/farzadhayat/"
