baseURL: https://farzadhayat.dev
languageCode: en-us
title: Farzad Hayat
theme: PaperMod

params:
  homeInfoParams:
    Title: "G'day ðŸ‘‹"
    Content: "I am a final-semester **Computer Science** student at **QUT** with experience as a **Software Engineer Intern at Tanda**. I specialize in building cloud-native, AI-powered applications and am seeking **Graduate Software Engineer** roles starting **July 2026**. In my free time, I enjoy partner dancing, cooking, and exploring open-source software."

  socialIcons:
    - name: "Email"
      url: "mailto:hello@farzadhayat.dev"
    - name: "GitHub"
      url: "https://github.com/FarzadHayat/"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/farzadhayat/"
